### PR TITLE
Copy to clipboard for codeblocks

### PR DESCRIPTION
**Pull request by oraNod**
Adds copy to clipboard hover for codeblocks. 

After merge, need to update title html to link to js and css assets:

```
<link rel="stylesheet" href="/assets/css/clipboard.css">
<script src="/assets/javascript/clipboard.min.js" type="text/javascript"></script>
<script src="/assets/javascript/copy.js" type="text/javascript"></script>
```

### CODE REVIEW

**Comment by oraNod** [comment]
This is preview until the styling is improved. Currently it's just a clickable "Copy" on each codeblock:

image


The ideal is to show a clipboard or other icon on hover.

**Comment by tristantarrant** [comment]
ideally we should be using fontawesome icons, like https://fontawesome.com/search?q=copy&s=brands%2Cregular

**Comment by tristantarrant** [comment]
Apparently we already have FontAwesome in there, so it's just a matter of getting `<i class="fa icon-copy" title="Copy"></i>

**Comment by insectengine** [comment]
screengrab

**Comment by oraNod** [comment]
@insectengine Awesome. Thank you!!

image


image

**Comment by oraNod** [comment]
@insectengine Sorry to hear about the frustration. Was the site not building locally with Jekyll or was it trying to insert the clipboard into a document?

If the latter then we'll need to do that in a separate PR to reference the js and css in the HTML pages for the docs. With this PR you need to manually add to `.html` in the docs directory:

```
<link rel="stylesheet" href="/assets/css/clipboard.css">
<script src="/assets/javascript/clipboard.min.js" type="text/javascript"></script>
<script src="/assets/javascript/copy.js" type="text/javascript"></script>
```

I'm also evaluating how we can use assets/main.css in the docs. I'd like to switch to that instead of having separate stylesheets but think that's an area where more work is required.

**Comment by oraNod** [comment]
@tristantarrant and @karesti We still need to modify the css files for html titles in core but this PR is ready. I'll hook it into the docs separately. I also want to remove `$` from code blocks.

**Comment by oraNod** [comment]
@karesti Yes, please!

**Pull request merged**
