### PR TITLE
Cross Site Replication should be under Server

### PR DESCRIPTION
**Pull request by karesti**

### CODE REVIEW

**Comment by pruivo** [comment]
the cross-site docs affect both embedded and server. IMO, it does not make sense to be under "Server"

**Comment by karesti** [comment]
@pruivo the guide then is misleading since it mixes many things. refers to operations like cli and rest api among others, and setting up clusters pointing to the Infinispan server. For me it does not make any sense from a developer perspective, but configuration, administration perspective.

**Comment by karesti** [comment]
@pruivo anyway, I opened a jira for @oraNod since the "developer" guide IMO is confusing as it is, since it mixes hotrod and embedded in the same guide. However, a java client guide exists, and we should be separating both since they respond to really different use cases and way of working in Infinispan. 
https://issues.redhat.com/browse/ISPN-13197

**Comment by pruivo** [comment]
> @pruivo the guide then is misleading since it mixes many things. refers to operations like cli and rest api among others, and setting up clusters pointing to the Infinispan server. For me it does not make any sense from a developer perspective, but a configuration, administration perspective.

The cli & rest admin commands already exist in the server guide and it doesn't need a second copy under the server category. We can just remove them from the "developer" category if it is causing confusion

**Comment by karesti** [comment]
@pruivo I think we need to wait for @oraNod to be back and discuss

**Comment by oraNod** [comment]
@karesti yeah, tbh I've felt the xsite doc doesn't belong under the "Developer" category so much. neither does it belong under "Admin" even though that is appropriate for some topics. 

Perhaps the best course of action is to merge this PR then move any content related to embedded caches to the "Embedding Infinispan" guide. That way the xsite guide will be focused on remote caches. Does that make sense?

**Comment by karesti** [comment]
@oraNod it does for me. WDYT @pruivo ?

**Comment by pruivo** [comment]
> @karesti yeah, tbh I've felt the xsite doc doesn't belong under the "Developer" category so much. neither does it belong under "Admin" even though that is appropriate for some topics.

Why not @oraNod ? The configuration steps are the same for embedded & server (same schema for jgroups stack and for caches)

My suggestion was to remove 3.1 & 3.2 (https://infinispan.org/docs/stable/titles/xsite/xsite.html#xsite_manage) since a copy of them already exist in the REST/CLI guides.

**Comment by oraNod** [comment]
> > @karesti yeah, tbh I've felt the xsite doc doesn't belong under the "Developer" category so much. neither does it belong under "Admin" even though that is appropriate for some topics.
> 
> Why not @oraNod ? The configuration steps are the same for embedded & server (same schema for jgroups stack and for caches)
> 
> My suggestion was to remove 3.1 & 3.2 (https://infinispan.org/docs/stable/titles/xsite/xsite.html#xsite_manage) since a copy of them already exist in the REST/CLI guides.

I see. I think it's good that we have a standalone doc for the killer use case of cross-site. I want to keep that for sure but I do kind of feel like the guide has been "lumped" into the Developer category on the docs home page.

I've been looking at the need to separate remote caches from embedded caches more in the doc set. I think that might be part of the issue here too. As you say the configuration is the same for remote vs embedded. So I guess there are a couple things going on. Maybe I should get ISPN-13197 done before we make this change.

**Pull request closed without merging**
