### PR TITLE
Remove ruby racer and fix release date

### PR DESCRIPTION
**Pull request by galderz**

### CODE REVIEW

**Comment by gustavonalle** [comment]
I tried a preview of the site using docker and got back:
```
An error occurred: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/home/dev/.gems/gems/execjs-2.6.0/lib/execjs/runtimes.rb:48:in `autodetect'
/home/dev/.gems/gems/execjs-2.6.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/dev/.gems/gems/execjs-2.6.0/lib/execjs.rb:4:in `<top (required)>'
/home/dev/.gems/gems/uglifier-2.0.1/lib/uglifier.rb:3:in `require'
/home/dev/.gems/gems/uglifier-2.0.1/lib/uglifier.rb:3:in `<top (required)>'
/home/dev/infinispan.github.io/_ext/js_minifier.rb:1:in `require'
/home/dev/infinispan.github.io/_ext/js_minifier.rb:1:in `<top (required)>'
/home/dev/infinispan.github.io/_ext/pipeline.rb:2:in `require'
/home/dev/infinispan.github.io/_ext/pipeline.rb:2:in `load_pipeline'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/lib/awestruct/engine.rb:254:in `eval'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/lib/awestruct/engine.rb:254:in `load_pipeline'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/lib/awestruct/engine.rb:67:in `run'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/generate.rb:21:in `run'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:126:in `invoke_generate'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:50:in `invoke!'
/home/dev/.gems/gems/awestruct-0.5.7.RC2/bin/awestruct:9:in `<top (required)>'
/home/dev/.gems/bin/awestruct:23:in `load'
/home/dev/.gems/bin/awestruct:23:in `<main>'
```
with a Internal Server Error in the browser. Are you able to preview in your environment?

**Comment by gustavonalle** [comment]
Apparently the problem was caused by this PR, it works in the ```developer``` branch

**Comment by danberindei** [comment]
I'm guessing this means we still need `therubyracer`...

**Comment by galderz** [comment]
@danberindei @gustavonalle Where does therubyracer dependency come from? IOW, what is it used for? According to the awestruct guys, [therubyracer is not an awestruct dependency](https://github.com/awestruct/awestruct/issues/502#issuecomment-161792715).

I was able to preview locally running:

    $ bundle install
    $ bundle exec awestruct -d --force -b 0.0.0.0

**Comment by gustavonalle** [comment]
@galderz Not sure where it comes from, but preview in docker fails after a ```rake clean preview```

**Comment by danberindei** [comment]
@galderz @gustavonalle have a look in `/infinispan.github.io/_ext/js_minifier.rb`

**Comment by galderz** [comment]
@danberindei @gustavonalle Thanks, I'm heading back to check with the Awestruct guys about `js_minifier` and `therubyracer`.

**Pull request closed without merging**
