### PR TITLE
Add Operator 2.2 docs

### PR DESCRIPTION
**Pull request by oraNod**

### CODE REVIEW

**Comment by oraNod** [comment]
@ryanemerson What do you think about changing the context for the operator docs so we have `dev` instead of `main`? And then also adding `stable` to follow the same convention as the core docs?

This would help SEO because the other `1.x` and `2.x` branches won't get indexed. Having `dev` and `stable` urls that get indexed is the way to go.

**Comment by ryanemerson** [comment]
Sure, sounds good to me!

**Comment by oraNod** [comment]
@ryanemerson Should be good to go here. After some further experimentation I think it's better to stick with what we've got but just indicate which branch is "stable" from the version selector. With this PR users will get the following options from the drop-down:

main
2.2.x (stable)
2.1.x
2.0.x
1.1.x

**Comment by ryanemerson** [comment]
Thanks @oraNod

**Pull request merged**
