### PR TITLE
Infinispan release 13.0.9.Final

### PR DESCRIPTION
**Pull request by pruivo**

### CODE REVIEW

**Review by oraNod — APPROVED** [review]

**Comment by oraNod** [comment]
@pruivo LGTM. Should I go ahead and merge now?

**Comment by pruivo** [comment]
let's wait for the images :)

**Comment by pruivo** [comment]
images released: https://quay.io/repository/infinispan/server?tab=tags

**Comment by oraNod** [comment]
Thanks @pruivo

**Pull request merged**
